"""Verify that `pyproject.toml` encodes the project's policies, not just metadata.

The zero-budget rule (ADR-0003) is easy to state and easy to erode: one
convenient paid client library added to `dependencies` and the runtime is no
longer free. Parsing the manifest and asserting the dependency list is empty
turns that policy into something CI can catch.
"""

import tomllib
from pathlib import Path
from typing import Any

import pytest

import globin
from tests.support import spelled_size


@pytest.fixture(scope="session")
def pyproject(repo_root: Path) -> dict[str, Any]:
    """Parsed `pyproject.toml` (stdlib `tomllib`; no third-party parser needed)."""
    with (repo_root / "pyproject.toml").open("rb") as handle:
        data: dict[str, Any] = tomllib.load(handle)
    return data


def test_distribution_name_matches_the_package(pyproject: dict[str, Any]) -> None:
    assert pyproject["project"]["name"] == globin.PACKAGE_NAME == "globin"


def test_every_runtime_dependency_has_a_written_review(
    repo_root: Path, pyproject: dict[str, Any]
) -> None:
    """Nothing runs in the runtime without a recorded decision to permit it.

    This test used to assert `dependencies == []`, which was the invariant from
    Phase 001 to Phase 020 and the friction ADR-0003 wanted: ending it had to be
    a deliberate edit to a test rather than a line added to a manifest. Phase 021
    ended it, and replacing the assertion with a weaker one — "the list is
    non-empty", or nothing at all — would have spent the friction and bought
    nothing.

    So it is stronger instead. The declared set and the reviewed set are compared
    in both directions, which catches the two failures that actually matter: a
    dependency added without the six-question review in
    `docs/engineering/dependency-reviews.toml`, and a review left behind for
    something no longer declared. Neither is caught by counting.
    """
    declared = {
        entry.split("[")[0].split(">")[0].split("=")[0].split("<")[0].split(";")[0].strip()
        for entry in pyproject["project"]["dependencies"]
    }
    with (repo_root / "docs" / "engineering" / "dependency-reviews.toml").open("rb") as handle:
        register = tomllib.load(handle)
    reviewed = {
        str(review["name"]) for review in register["review"] if review["scope"] == "runtime"
    }
    assert declared == reviewed


def test_the_runtime_lock_accompanies_the_runtime_dependencies(
    repo_root: Path, pyproject: dict[str, Any]
) -> None:
    """A declared runtime dependency and `pylock.toml` arrive together.

    `tools/quality/lock` enforces the same pairing with a reason code, and this
    asserts it in the ordinary suite so that a commit separating the two fails
    before anybody runs the lock gate. The two checks are not a duplicate: that
    one reads the lock and recomputes its claims, and this one only asks whether
    the file is there at all.
    """
    if not pyproject["project"]["dependencies"]:
        pytest.skip("nothing is declared, so nothing needs locking")
    assert (repo_root / "pylock.toml").is_file(), (
        "project.dependencies is non-empty and pylock.toml is missing; "
        "produce it with `python -m tools.quality.lock relock`"
    )


def test_one_console_entry_point_is_declared(pyproject: dict[str, Any]) -> None:
    """`globin` is the command, and it delegates to the CLI's `main`.

    Asserted rather than assumed because the console script is generated by the
    build backend from this string: a typo here produces a command that installs
    cleanly and fails on first use, which is the worst time to find out.
    """
    assert pyproject["project"]["scripts"] == {"globin": "globin.runtime.cli:main"}


def test_development_extra_is_a_free_toolchain(pyproject: dict[str, Any]) -> None:
    """The exact set, so that adding a tool is a change someone has to read.

    ADR-0003 exempts development tooling from the zero-budget rule, which makes
    this list the only place the exemption is bounded. `hypothesis` joined it in
    Phase 005 (ADR-0023); it is MPL-2.0 and pulls in one Apache-2.0 dependency.
    """
    dev = pyproject["project"]["optional-dependencies"]["dev"]
    names = {entry.split(">")[0].split("=")[0].split("[")[0].strip() for entry in dev}
    assert names == {
        "pytest",
        "pytest-cov",
        "ruff",
        "mypy",
        "pre-commit",
        "hypothesis",
        "pip-audit",
    }


def test_contributing_names_every_development_dependency(
    repo_root: Path, pyproject: dict[str, Any]
) -> None:
    """`CONTRIBUTING.md` restates the toolchain, and restatements go stale.

    This one had. `hypothesis` joined the dev extra in Phase 005 and the document
    went on listing five tools and calling them "four" until Phase 007 read it —
    which is the whole argument for binding a restatement rather than trusting
    it. The spelled size is checked as well as the names, because the number is
    the half a reader believes without counting.
    """
    document = (repo_root / "CONTRIBUTING.md").read_text(encoding="utf-8")
    dev = pyproject["project"]["optional-dependencies"]["dev"]
    names = sorted({entry.split(">")[0].split("=")[0].split("[")[0].strip() for entry in dev})

    unnamed = [name for name in names if f"`{name}`" not in document]
    assert not unnamed, f"CONTRIBUTING.md does not name the development tools: {unnamed}"

    spelled = spelled_size(len(names))
    assert f"All {spelled} are free and open source" in document, (
        f"CONTRIBUTING.md must say 'All {spelled} are free and open source' "
        f"for a toolchain of {len(names)}"
    )


def test_requires_python_floor_supports_the_planned_stack(pyproject: dict[str, Any]) -> None:
    """3.12 is the strictest known floor among libraries scheduled for later phases.

    See docs/research/phase_001_sources.md — XGBoost requires >=3.12 while
    PyTorch, Gymnasium and Stable-Baselines3 require >=3.10.
    """
    assert pyproject["project"]["requires-python"] == ">=3.12"


def test_version_is_dynamic_and_sourced_from_the_package(
    repo_root: Path, pyproject: dict[str, Any]
) -> None:
    assert pyproject["project"]["dynamic"] == ["version"]
    version_path = pyproject["tool"]["hatch"]["version"]["path"]
    assert version_path == "src/globin/__init__.py"
    assert (repo_root / version_path).is_file()
    assert f'__version__ = "{globin.__version__}"' in (repo_root / version_path).read_text(
        encoding="utf-8"
    )


def test_no_licence_is_asserted(pyproject: dict[str, Any]) -> None:
    """Licensing is deliberately undecided and must not be invented.

    The owner has not selected a licence. Declaring one here would be a legal
    assertion the project is not entitled to make, so its absence is checked.
    """
    project = pyproject["project"]
    assert "license" not in project
    assert "license-files" not in project


def test_src_layout_is_configured(repo_root: Path, pyproject: dict[str, Any]) -> None:
    assert pyproject["tool"]["hatch"]["build"]["targets"]["wheel"]["packages"] == ["src/globin"]
    # `"."` joined `"src"` in Phase 004, when `tests` became a package and the
    # quality entrypoint arrived under `tools/`. Both are imported by name, so
    # the repository root has to be on the path deliberately rather than by
    # accident of where pytest happens to start.
    assert pyproject["tool"]["pytest"]["ini_options"]["pythonpath"] == ["src", "."]
    assert (repo_root / "src" / "globin" / "__init__.py").is_file()


#: The flags `mypy --strict` expanded to on the version Phase 004 was written
#: against, restated literally. This is a tripwire in the sense
#: `SOURCE_OF_TRUTH.md` permits: the copy exists so that quietly dropping a flag
#: from `pyproject.toml` fails here rather than silently weakening the contract.
STRICT_MYPY_FLAGS: tuple[str, ...] = (
    "disallow_any_generics",
    "disallow_subclassing_any",
    "disallow_untyped_calls",
    "disallow_untyped_defs",
    "disallow_incomplete_defs",
    "check_untyped_defs",
    "disallow_untyped_decorators",
    "warn_redundant_casts",
    "warn_unused_ignores",
    "warn_return_any",
    "strict_equality",
    "extra_checks",
)


def test_strict_typing_is_declared_flag_by_flag(pyproject: dict[str, Any]) -> None:
    """Typing strictness must be spelled out, not delegated to `strict = true`.

    `--strict` is an alias mypy owns. Its membership has changed between
    releases and will change again, so under the alias a mypy upgrade can add or
    remove a check with no diff to read and no decision to review. Writing the
    flags out costs a dozen lines and makes the contract mean the same thing
    tomorrow as it does today.
    """
    mypy = pyproject["tool"]["mypy"]
    assert "strict" not in mypy, (
        "`strict = true` is back in pyproject.toml; it hides which checks are actually on"
    )
    missing = [flag for flag in STRICT_MYPY_FLAGS if mypy.get(flag) is not True]
    assert not missing, f"typing strictness weakened; these flags are not enabled: {missing}"
    assert mypy["implicit_reexport"] is False, "implicit re-export must stay disabled"


def test_untyped_ignores_are_rejected(pyproject: dict[str, Any]) -> None:
    """A bare `# type: ignore` silences errors nobody has seen yet.

    Requiring the code makes each suppression name the thing it suppresses,
    which is the difference between an exception and a blind spot.
    """
    enabled = pyproject["tool"]["mypy"]["enable_error_code"]
    assert "ignore-without-code" in enabled


def test_line_length_is_configured_once(pyproject: dict[str, Any]) -> None:
    assert pyproject["tool"]["ruff"]["line-length"] == 100
